#!/bin/bash
# DO NOT EDIT in forked projects. This file is maintained in the upstream template repository.
set -euo pipefail

# ============================================================
# Project Setup Script
#
# Reads PROJECT_NAME and PROJECT_NUMBER from .env, then:
#   1. Calculates host ports (21000-24999 range, based on N)
#   2. Derives DB_NAME from PROJECT_NAME (kebab → snake_case)
#   3. Writes computed values back to .env
#   4. Updates static project name references in source files
#   5. Generates .dev.vars for wrangler
#
# Usage:
#   1. cp .env.example .env
#   2. Edit .env (set PROJECT_NAME and PROJECT_NUMBER)
#   3. ./setup.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env file not found."
  echo "Run 'cp .env.example .env' and edit it first."
  exit 1
fi

# Source .env
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

PROJECT_NAME="${PROJECT_NAME:?PROJECT_NAME is not set in .env}"
PROJECT_NUMBER="${PROJECT_NUMBER:?PROJECT_NUMBER is not set in .env}"

# Validate project number
if ! [[ "$PROJECT_NUMBER" =~ ^[0-9]+$ ]] || [ "$PROJECT_NUMBER" -lt 1 ] || [ "$PROJECT_NUMBER" -gt 99 ]; then
  echo "Error: PROJECT_NUMBER must be an integer between 1 and 99"
  exit 1
fi

# Validate project name (kebab-case)
if ! [[ "$PROJECT_NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
  echo "Error: PROJECT_NAME must be kebab-case (e.g. my-cool-app)"
  exit 1
fi

# ---- Derive values ----

KEBAB="$PROJECT_NAME"
DB_NAME=$(echo "$KEBAB" | tr '-' '_')
PASCAL=$(echo "$KEBAB" | sed -E 's/(^|-)(\w)/\U\2/g')
TITLE=$(echo "$KEBAB" | sed -E 's/-/ /g; s/\b(\w)/\U\1/g')

# Calculate host ports
# Web 1-10:         21000+N ~ 21900+N
# API 1-10:         22000+N ~ 22900+N
# Auth 1-5:         23000+N ~ 23400+N
# DB 1-5:           23500+N ~ 23900+N
# Stripe 1-5:       24000+N ~ 24400+N
# Stripe HTTPS 1-5: 24500+N ~ 24900+N

# Web (Vite) — 10 slots
for i in $(seq 1 10); do
  declare "PORT_WEB_${i}=$(( 21000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# API (Wrangler) — 10 slots
for i in $(seq 1 10); do
  declare "PORT_API_${i}=$(( 22000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# Auth (GoTrue) — 5 slots
for i in $(seq 1 5); do
  declare "PORT_AUTH_${i}=$(( 23000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# DB (PostgreSQL) — 5 slots
for i in $(seq 1 5); do
  declare "PORT_DB_${i}=$(( 23500 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# Stripe Mock — 5 slots
for i in $(seq 1 5); do
  declare "PORT_STRIPE_${i}=$(( 24000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# Stripe HTTPS — 5 slots
for i in $(seq 1 5); do
  declare "PORT_STRIPE_HTTPS_${i}=$(( 24500 + (i - 1) * 100 + PROJECT_NUMBER ))"
done


echo "============================================="
echo "  Setting up: $KEBAB (N=$PROJECT_NUMBER)"
echo "============================================="
echo ""
echo "  DB name:      $DB_NAME"
echo "  PascalCase:   $PASCAL"
echo "  Title:        $TITLE"
echo ""
echo "  Host ports:"
for i in $(seq 1 10); do
  var="PORT_WEB_${i}"
  echo "    Web $i (Vite):      localhost:${!var}"
done
for i in $(seq 1 10); do
  var="PORT_API_${i}"
  echo "    API $i (Wrangler):  localhost:${!var}"
done
for i in $(seq 1 5); do
  var="PORT_AUTH_${i}"
  echo "    Auth $i (GoTrue):   localhost:${!var}"
done
for i in $(seq 1 5); do
  var="PORT_DB_${i}"
  echo "    DB $i (PostgreSQL): localhost:${!var}"
done
for i in $(seq 1 5); do
  var="PORT_STRIPE_${i}"
  echo "    Stripe $i (Mock):   localhost:${!var}"
done
for i in $(seq 1 5); do
  var="PORT_STRIPE_HTTPS_${i}"
  echo "    Stripe $i (HTTPS):  localhost:${!var}"
done
echo ""

# ---- Write computed values back to .env ----

{
  echo "# Project Configuration (generated by setup.sh)"
  echo "PROJECT_NAME=$KEBAB"
  echo "PROJECT_NUMBER=$PROJECT_NUMBER"
  echo "DB_NAME=$DB_NAME"
  echo ""
  echo "# Web (Vite) ports — 10 slots"
  for i in $(seq 1 10); do
    var="PORT_WEB_${i}"
    echo "PORT_WEB_${i}=${!var}"
  done
  echo ""
  echo "# API (Wrangler) ports — 10 slots"
  for i in $(seq 1 10); do
    var="PORT_API_${i}"
    echo "PORT_API_${i}=${!var}"
  done
  echo ""
  echo "# Auth (GoTrue) ports — 5 slots"
  for i in $(seq 1 5); do
    var="PORT_AUTH_${i}"
    echo "PORT_AUTH_${i}=${!var}"
  done
  echo ""
  echo "# DB (PostgreSQL) ports — 5 slots"
  for i in $(seq 1 5); do
    var="PORT_DB_${i}"
    echo "PORT_DB_${i}=${!var}"
  done
  echo ""
  echo "# Stripe Mock ports — 5 slots"
  for i in $(seq 1 5); do
    var="PORT_STRIPE_${i}"
    echo "PORT_STRIPE_${i}=${!var}"
  done
  echo ""
  echo "# Stripe HTTPS ports — 5 slots"
  for i in $(seq 1 5); do
    var="PORT_STRIPE_HTTPS_${i}"
    echo "PORT_STRIPE_HTTPS_${i}=${!var}"
  done
  echo ""
  echo "# Docker Compose files"
  echo "COMPOSE_FILE=${COMPOSE_FILE:-docker-compose.yml}"
  echo ""
  echo "# Credentials"
  echo "POSTGRES_USER=${POSTGRES_USER:-postgres}"
  echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
  echo "JWT_SECRET=${JWT_SECRET:-super-secret-jwt-token-for-testing-only-change-in-production}"
  echo "SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzM0Nzc0ODQsImV4cCI6MTgwNTAxMzQ4NH0.n7ZYnCpC0vEi8OrslntStIac2eIcqZjwFXT9G2frDZM}"
} > "$ENV_FILE"

# ---- Update static project names ----

# package.json (root)
sed -i.bak 's/"name": "my-saas"/"name": "'"$KEBAB"'"/' "$SCRIPT_DIR/package.json"

# apps/api/package.json
sed -i.bak 's/"name": "@my-saas\/api"/"name": "@'"$KEBAB"'\/api"/' "$SCRIPT_DIR/apps/api/package.json"

# apps/web/package.json
sed -i.bak 's/"name": "@my-saas\/web"/"name": "@'"$KEBAB"'\/web"/' "$SCRIPT_DIR/apps/web/package.json"

# apps/api/wrangler.toml
sed -i.bak 's/^name = "my-saas-api"/name = "'"$KEBAB"'-api"/' "$SCRIPT_DIR/apps/api/wrangler.toml"

# apps/web/public/manifest.json
sed -i.bak 's/"name": "My SaaS"/"name": "'"$TITLE"'"/' "$SCRIPT_DIR/apps/web/public/manifest.json"
sed -i.bak 's/"short_name": "MySaaS"/"short_name": "'"$PASCAL"'"/' "$SCRIPT_DIR/apps/web/public/manifest.json"

# apps/web/index.html (page title)
sed -i.bak 's/<title>My SaaS<\/title>/<title>'"$TITLE"'<\/title>/' "$SCRIPT_DIR/apps/web/index.html"

# ---- Generate .dev.vars for wrangler ----

cat > "$SCRIPT_DIR/apps/api/.dev.vars" <<EOF
DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${DB_NAME}
SUPABASE_URL=http://auth:9999
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzM0Nzc0ODQsImV4cCI6MTgwNTAxMzQ4NH0.n7ZYnCpC0vEi8OrslntStIac2eIcqZjwFXT9G2frDZM}
JWT_SECRET=${JWT_SECRET:-super-secret-jwt-token-for-testing-only-change-in-production}
STRIPE_SECRET_KEY=sk_test_mock
STRIPE_API_BASE_URL=http://stripe-mock:12111/v1
EOF

# ---- Cleanup .bak files ----

find "$SCRIPT_DIR" -name "*.bak" -delete

echo "Done! Project '$KEBAB' is ready."
echo ""
echo "Next steps:"
echo "  docker-compose up -d"
echo "  ./dev-exec.sh"
echo "  pnpm install"
echo "  pnpm db:push"
echo "  cd apps/api && npm run dev:seed"
echo "  pnpm dev"
