#!/bin/bash
# DO NOT EDIT in forked projects. This file is maintained in the upstream template repository.
set -euo pipefail

# ============================================================
# Project Setup Script
#
# Reads PROJECT_NAME and PROJECT_NUMBER from .env, then:
#   1. Calculates host ports (21000-24999 range, based on N)
#   2. Writes computed values back to .env
#   3. Updates static project name references in source files
#
# Usage:
#   1. cp .env.example .env
#   2. Edit .env (set PROJECT_NAME and PROJECT_NUMBER)
#   3. ./setup.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: .env file not found."
  echo "Run 'cp .env.example .env' and edit it first."
  exit 1
fi

# Source .env
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

PROJECT_NAME="${PROJECT_NAME:?PROJECT_NAME is not set in .env}"
PROJECT_NUMBER="${PROJECT_NUMBER:?PROJECT_NUMBER is not set in .env}"

# Validate project number
if ! [[ "$PROJECT_NUMBER" =~ ^[0-9]+$ ]] || [ "$PROJECT_NUMBER" -lt 1 ] || [ "$PROJECT_NUMBER" -gt 99 ]; then
  echo "Error: PROJECT_NUMBER must be an integer between 1 and 99"
  exit 1
fi

# Validate project name (kebab-case)
if ! [[ "$PROJECT_NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
  echo "Error: PROJECT_NAME must be kebab-case (e.g. my-cool-app)"
  exit 1
fi

# ---- Derive values ----

KEBAB="$PROJECT_NAME"
PASCAL=$(echo "$KEBAB" | sed -E 's/(^|-)(\w)/\U\2/g')
TITLE=$(echo "$KEBAB" | sed -E 's/-/ /g; s/\b(\w)/\U\1/g')

# Calculate host ports
# Web 1-10:         21000+N ~ 21900+N
# API 1-10:         22000+N ~ 22900+N

# Web (Vite) — 10 slots
for i in $(seq 1 10); do
  declare "PORT_WEB_${i}=$(( 21000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done

# API (Wrangler) — 10 slots
for i in $(seq 1 10); do
  declare "PORT_API_${i}=$(( 22000 + (i - 1) * 100 + PROJECT_NUMBER ))"
done


echo "============================================="
echo "  Setting up: $KEBAB (N=$PROJECT_NUMBER)"
echo "============================================="
echo ""
echo "  PascalCase:   $PASCAL"
echo "  Title:        $TITLE"
echo ""
echo "  Host ports:"
for i in $(seq 1 10); do
  var="PORT_WEB_${i}"
  echo "    Web $i (Vite):      localhost:${!var}"
done
for i in $(seq 1 10); do
  var="PORT_API_${i}"
  echo "    API $i (Wrangler):  localhost:${!var}"
done
echo ""

# ---- Write computed values back to .env ----

{
  echo "# Project Configuration (generated by setup.sh)"
  echo "PROJECT_NAME=$KEBAB"
  echo "PROJECT_NUMBER=$PROJECT_NUMBER"
  echo ""
  echo "# Web (Vite) ports — 10 slots"
  for i in $(seq 1 10); do
    var="PORT_WEB_${i}"
    echo "PORT_WEB_${i}=${!var}"
  done
  echo ""
  echo "# API (Wrangler) ports — 10 slots"
  for i in $(seq 1 10); do
    var="PORT_API_${i}"
    echo "PORT_API_${i}=${!var}"
  done
  echo ""
  echo "# Docker Compose files"
  echo "COMPOSE_FILE=${COMPOSE_FILE:-docker-compose.yml}"
} > "$ENV_FILE"

# ---- Update static project names ----

# package.json (root)
sed -i.bak 's/"name": "my-saas"/"name": "'"$KEBAB"'"/' "$SCRIPT_DIR/package.json"

# apps/api/package.json
sed -i.bak 's/"name": "@my-saas\/api"/"name": "@'"$KEBAB"'\/api"/' "$SCRIPT_DIR/apps/api/package.json"

# apps/web/package.json
sed -i.bak 's/"name": "@my-saas\/web"/"name": "@'"$KEBAB"'\/web"/' "$SCRIPT_DIR/apps/web/package.json"

# apps/api/wrangler.toml
sed -i.bak 's/^name = "my-saas-api"/name = "'"$KEBAB"'-api"/' "$SCRIPT_DIR/apps/api/wrangler.toml"

# apps/web/public/manifest.json
sed -i.bak 's/"name": "My SaaS"/"name": "'"$TITLE"'"/' "$SCRIPT_DIR/apps/web/public/manifest.json"
sed -i.bak 's/"short_name": "MySaaS"/"short_name": "'"$PASCAL"'"/' "$SCRIPT_DIR/apps/web/public/manifest.json"

# apps/web/index.html (page title)
sed -i.bak 's/<title>My SaaS<\/title>/<title>'"$TITLE"'<\/title>/' "$SCRIPT_DIR/apps/web/index.html"

# ---- Cleanup .bak files ----

find "$SCRIPT_DIR" -name "*.bak" -delete

echo "Done! Project '$KEBAB' is ready."
echo ""
echo "Next steps:"
echo "  docker-compose up -d"
echo "  ./dev-exec.sh"
echo "  pnpm install"
echo "  pnpm dev"
